version: '3.8'
services:
  backend:
    image: ruslanxx/chat-backend:latest
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: ruslanxx/chat-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend